### ISSUE TITLE
collect vslam learning resources

### ISSUE THREAD

**Issue by castiel520** [castiel520/vslam_research#1]

**Comment by pengfei666** [comment]
learn <视觉SLAM十四讲-第七讲>

**Comment by castiel520** [comment]
* 视觉SLAM十四讲 by gx
* Multiple View Geometry by TUM you can acesss it by [\\FLUYT\TUMslides](\\FLUYT\TUMslides) @pengfei666 
*  链接/博客  
    * [heyijia的博客](http://blog.csdn.net/heyijia0327) 
    * [openSLAM](https://github.com/OpenSLAM) 
    *  [高翔的博客](http://www.cnblogs.com/gaoxiang12/) 
    *  [TUM](http://vision.in.tum.de)
    *  [orb_slam2代码详解](http://Git.oschina.net/paopaoslam/ORB-SLAM2)
    *  [slamcn](http://www.slamcn.org/) 
    *  [状态估计](http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser15.pdf) 
    *  [hitcm的博客](http://www.cnblogs.com/hitcm/)

**Comment by castiel520** [comment]
### open source slam projects:

- [**ORB_SLAM2**](https://github.com/raulmur/ORB_SLAM2)
- [**DSO**](https://github.com/JakobEngel/dso)
- [**DTAM**](https://github.com/anuranbaka/OpenDTAM)
- [**LSD_SLAM**](https://github.com/tum-vision/lsd_slam)
- [**ORB_AR**](https://github.com/ygx2011/Stereo_SLAM_AR)
